### ISSUE TITLE
Mod cet_mod_manager failed to load! 

### ISSUE THREAD

**Issue by MelonHell** [Nats-ji/CET-Mod-Manager#12]
Mod cet_mod_manager failed to load! ('D:\Games\Steam\steamapps\common\Cyberpunk 2077\bin\x64\plugins\cyber_engine_tweaks\mods\cet_mod_manager')

cet_mod_manager.log
`[2022-02-19 18:14:17 UTC+03:00] [error] [] sol: runtime error: ...lugins\cyber_engine_tweaks\mods\cet_mod_manager\init.lua:22: attempt to index global 'json' (a nil value)
stack traceback:
	...lugins\cyber_engine_tweaks\mods\cet_mod_manager\init.lua:22: in function 'check_module'
	...lugins\cyber_engine_tweaks\mods\cet_mod_manager\init.lua:231: in main chunk`

Windows 11
Cyberpunk 1.5 and 1.5-hotfix
CET 1.9.0 and 1.9.1

**Comment by Nats-ji** [comment]
please try the new release
https://github.com/Nats-ji/CET-Mod-Manager/releases

**Comment by MelonHell** [comment]
Thanks for the reply, I'm happy with the new version.

I forgot to write, the problem has already been solved, although I still did not understand what it was. The solution was that I removed everything related to Lua from my computer.

**Comment by Nats-ji** [comment]
maybe its caused by a game crash that corrupted some lua scripts. i think the new version should be more reliable now
